language: python
python:
  - "pypy3.5"
install:
  - source ~/virtualenv/python3.6/bin/activate
  - pip install mypy flake8
script:
  - git clone https://github.com/hase-project ~/hase
  - MYPYPATH=~/hase PATH=~/virtualenv/pypy3.5/bin:$PATH mypy bugdb bin
  - flake8 hase
branches:
  only:
  - master
